"""
Maritime - a continuous-coordinate sailing and vessel simulation for Evennia.

Vessels are simulation entities holding a position in continuous world space.
Their interiors remain ordinary Evennia rooms, which move with the vessel rather
than determining where it is.

Commonly used names are re-exported here, so games can import them directly:

    from evennia.contrib.full_systems.maritime import GameTimeProvider

"""

from . import config  # noqa: F401
from .bathymetry import (
    DATUM,
    FlatSeaMapProvider,
    FlatTideProvider,
    MaritimeMapProvider,
    MaritimeTideProvider,
)
from .charts import (
    Chart,
    best_chart_for,
    charted_bottom_at,
    charted_depth_at,
    charted_terrain_z_at,
)
from .clock import GameTimeProvider, ManualTimeProvider, MaritimeTimeProvider
from .currents import (
    STILL,
    CurrentVector,
    FlatCurrentProvider,
    MaritimeCurrentProvider,
    carried,
    course_to_steer,
    drift_offset,
    made_good,
)
from .events import Delivery, Event, EventBus
from .cmdsets import HelmCmdSet
from .commands import CmdAllStop, CmdHelm, CmdPosition, CmdSpeed
from .formatting import (
    METRES_PER_SECOND_PER_KNOT,
    DEPTH_UNITS,
    DISTANCE_UNITS,
    FATHOMS,
    LEAGUES,
    METRES,
    METRIC,
    NAUTICAL,
    RAW,
    format_depth,
    format_position,
    format_range,
)
from .messaging import (
    LEAD_LINE_FATHOMS,
    LEAD_MARKS,
    leadsman_call,
    AT_SPEED,
    COMING_ROUND,
    HULL_HOLED,
    RUN_AGROUND,
    SHOALING,
    STEADY,
    WAY_OFF,
    VesselNarrator,
    compass_point,
    spell_bearing,
)
from .grounding import (
    check_swept_grounding,
    hull_points,
    sweep_positions,
    AGROUND,
    HOLED,
    TOUCHED,
    GroundingResult,
    check_grounding,
    is_shoaling,
    keel_clearance,
    refloats_on_tide,
)
from .motion import HelmOrders, MotionLimits, MotionState, advance
from .navigation import (
    FIX_UNCERTAINTY,
    DeadReckoning,
    error_of,
    reckon,
    set_and_drift,
    take_fix,
)
from .observation import (
    CLASSIFIED,
    CONTACT,
    DETECTION_LEVELS,
    IDENTIFIED,
    Sighting,
    bearing_in_points,
    detection_level,
    detection_limit,
    geographic_range,
    horizon_distance,
    scan,
    sight,
)
from .tactical import (
    ARCS,
    arcs_bearing,
    aspect,
    aspect_name,
    bears,
    closure,
    crossing_the_t,
    range_band,
    relative_heading,
    time_to_close,
)
from .traffic import VesselTraffic, traffic
from .position import (
    DEFAULT_REGION,
    METRES_PER_CABLE,
    METRES_PER_FATHOM,
    METRES_PER_LEAGUE,
    METRES_PER_NAUTICAL_MILE,
    WorldPosition,
    bearing_difference,
    normalize_bearing,
)
from .resolver import (
    NoWorldPosition,
    get_world_position,
    has_world_position,
    resolve_chain,
)
from .voyage import approach_speed, course_for_mark, sail_for_wind
from .weapons import (
    Mount,
    ShotResult,
    WeaponType,
    aim_point,
    can_fire,
    discharge,
    fire,
    hit_chance,
    serve,
    time_of_flight,
)
from .cargo import (
    DEFAULT_BROKEN_STOWAGE,
    NEITHER,
    STANDARD_STOWAGE,
    VOLUME,
    WEIGHT,
    Commodity,
    Parcel,
    Stowage,
    binding_limit,
    combine,
    commodity_named,
    deadweight,
    freeboard,
    laden_draft,
    laden_speed,
    overloaded,
    room_for,
    sinkage,
    stowed_moment,
    stowed_volume,
    take_from,
    tender,
    tonnes_per_centimetre,
    total_tonnes,
)
from .stowage import Laden, Stowed, TransferResult
from .floating import (
    Buoyancy,
    Floating,
    BARREL_WINDAGE,
    DEBRIS_WINDAGE,
    RAFT_WINDAGE,
    SWIMMER_WINDAGE,
    UPTURNED_HULL_WINDAGE,
    drift,
    separation,
    sinking_depth,
    wind_drift,
)
from .projection import CELL_SIZE, OceanProjection, OceanRoom
from .weather import (
    SEA_STATES,
    FlatWeatherProvider,
    MaritimeWeatherProvider,
    Weather,
    sea_drag,
    sea_state_for,
)
from .vessel import (
    BELOW_WATERLINE,
    EXPOSURES,
    INTERIOR,
    MAIN_DECK,
    OPEN,
    SEMI_EXPOSED,
    DeckLevel,
    DeckPlan,
    VesselCapacity,
    VesselTemplate,
)
from .ports import (
    ALONGSIDE_SPEED,
    APPROACH_RANGE,
    Berth,
    DockingResult,
    alongside_side,
    can_dock,
    nearest_berth,
)
from .routes import NavigationNetwork, Route, Waypoint
from .rooms import (
    rig_grapples,
    PortRoom,
    ShipRoom,
    absent_from,
    berths_near,
    everyone_in,
    rig_gangway,
    unrig_gangway,
)
from .scheduler import FairQueue
from .sailing import (
    FULL,
    FURLED,
    REEFED,
    SAIL_PLANS,
    STORM,
    WORKING,
    PolarCurve,
    SailPlan,
    WindVector,
    achievable_speed,
    leeway_angle,
    relative_wind_angle,
    sail_plan,
)
from .scripts import MaritimeDriver
from .typeclasses import Flotsam, Vessel
from .simulation import (
    ACTIVE,
    DORMANT,
    STRATEGIC,
    TACTICAL,
    TIERS,
    TIER_INTERVALS,
    MaritimeSimulationService,
)
from .tiles import (
    DEFAULT_TILE_SIZE,
    UNMAPPED_TERRAIN_Z,
    DictTileSource,
    Hazard,
    Tile,
    TileSource,
    TiledMapProvider,
)
from .spatial import (
    ContactIndex,
    ProximityIndex,
    SpatialIndex,
    cell_bounds,
    cell_centre,
    cell_of,
    cells_touching,
    distance_to_track,
    nearest_on_track,
    track_entry,
)
from .oars import (
    EASY_OARS,
    GIVE_WAY,
    HOLD_WATER,
    OAR_PLANS,
    PADDLE,
    PADDLED,
    ROWED,
    STRETCH_OUT,
    STROKES,
    OarPlan,
    Oared,
    braking_limits,
    hands_available,
    reach,
    rowed_speed,
)
from .boarding import (
    GRAPNEL_RANGE,
    MAX_BOARDING_CLOSURE,
    MAX_HOLDING_CLOSURE,
    Boarded,
    GrappleResult,
    bears_alongside,
    can_grapple,
    relative_speed,
    still_holding,
    velocity,
    within_reach,
)
from .results import (
    INVALID_TARGET,
    NOT_PERMITTED,
    PRECONDITION_FAILED,
    UNSUPPORTED,
    Result,
)
from .rng import AI, COMBAT, DAMAGE, NAVIGATION, WEATHER, RNGContext

__all__ = (
    # configuration
    "config",
    # time
    "MaritimeTimeProvider",
    "GameTimeProvider",
    "ManualTimeProvider",
    # randomness
    "RNGContext",
    "NAVIGATION",
    "COMBAT",
    "DAMAGE",
    "WEATHER",
    "AI",
    # space
    "WorldPosition",
    "DATUM",
    "MaritimeMapProvider",
    "FlatSeaMapProvider",
    "MaritimeTideProvider",
    "FlatTideProvider",
    "get_world_position",
    "has_world_position",
    "resolve_chain",
    "NoWorldPosition",
    "SpatialIndex",
    "ContactIndex",
    "ProximityIndex",
    # simulation
    "MaritimeDriver",
    "Vessel",
    "Flotsam",
    "ShipRoom",
    "PortRoom",
    # navigation
    "Chart",
    "charted_depth_at",
    "charted_terrain_z_at",
    "charted_bottom_at",
    "best_chart_for",
    "Waypoint",
    "Route",
    "NavigationNetwork",
    "DeadReckoning",
    "reckon",
    "take_fix",
    "error_of",
    "set_and_drift",
    "FIX_UNCERTAINTY",
    # ports
    "Berth",
    "DockingResult",
    "can_dock",
    "nearest_berth",
    "alongside_side",
    "berths_near",
    "absent_from",
    "everyone_in",
    "rig_gangway",
    "rig_grapples",
    "unrig_gangway",
    "APPROACH_RANGE",
    "ALONGSIDE_SPEED",
    "MaritimeSimulationService",
    "FairQueue",
    "TIERS",
    "TIER_INTERVALS",
    "DORMANT",
    "STRATEGIC",
    "ACTIVE",
    "TACTICAL",
    # vessels
    "VesselTemplate",
    "VesselCapacity",
    "DeckPlan",
    "DeckLevel",
    "MAIN_DECK",
    "EXPOSURES",
    "OPEN",
    "SEMI_EXPOSED",
    "INTERIOR",
    "BELOW_WATERLINE",
    "normalize_bearing",
    "METRES_PER_NAUTICAL_MILE",
    "METRES_PER_CABLE",
    "METRES_PER_LEAGUE",
    "METRES_PER_FATHOM",
    "METRES_PER_SECOND_PER_KNOT",
    "bearing_difference",
    # commands
    "HelmCmdSet",
    "CmdHelm",
    "CmdSpeed",
    "CmdAllStop",
    "CmdPosition",
    # presentation
    "format_position",
    "format_range",
    "format_depth",
    "leadsman_call",
    "LEAD_MARKS",
    "LEAD_LINE_FATHOMS",
    "NAUTICAL",
    "RAW",
    "LEAGUES",
    "METRIC",
    "FATHOMS",
    "METRES",
    "DISTANCE_UNITS",
    "DEPTH_UNITS",
    "VesselNarrator",
    "compass_point",
    "spell_bearing",
    "COMING_ROUND",
    "STEADY",
    "AT_SPEED",
    "WAY_OFF",
    "RUN_AGROUND",
    "HULL_HOLED",
    "SHOALING",
    # currents
    "CurrentVector",
    "MaritimeCurrentProvider",
    "FlatCurrentProvider",
    "STILL",
    "carried",
    "drift_offset",
    "made_good",
    "course_to_steer",
    # the sailing master
    "course_for_mark",
    "sail_for_wind",
    "approach_speed",
    # weapons
    "WeaponType",
    "Mount",
    "ShotResult",
    "time_of_flight",
    "aim_point",
    "hit_chance",
    "can_fire",
    "fire",
    "serve",
    "discharge",
    # floating and the projected ocean
    "Floating",
    "Buoyancy",
    "drift",
    "wind_drift",
    "separation",
    "sinking_depth",
    "cell_of",
    "cell_centre",
    "cell_bounds",
    "cells_touching",
    "distance_to_track",
    "nearest_on_track",
    "track_entry",
    # map tiles
    "Tile",
    "Hazard",
    "TileSource",
    "DictTileSource",
    "TiledMapProvider",
    "DEFAULT_TILE_SIZE",
    "UNMAPPED_TERRAIN_Z",
    "SWIMMER_WINDAGE",
    "DEBRIS_WINDAGE",
    "BARREL_WINDAGE",
    "RAFT_WINDAGE",
    "UPTURNED_HULL_WINDAGE",
    "OceanRoom",
    "OceanProjection",
    "CELL_SIZE",
    # cargo
    "Commodity",
    "Parcel",
    "Stowage",
    "Stowed",
    "Laden",
    "TransferResult",
    "STANDARD_STOWAGE",
    "commodity_named",
    "combine",
    "take_from",
    "stowed_volume",
    "stowed_moment",
    "binding_limit",
    "room_for",
    "deadweight",
    "tonnes_per_centimetre",
    "sinkage",
    "laden_draft",
    "laden_speed",
    "freeboard",
    "overloaded",
    "tender",
    "total_tonnes",
    "WEIGHT",
    "VOLUME",
    "NEITHER",
    "DEFAULT_BROKEN_STOWAGE",
    # oars
    "OarPlan",
    "Oared",
    "OAR_PLANS",
    "STROKES",
    "rowed_speed",
    "hands_available",
    "braking_limits",
    "reach",
    "ROWED",
    "PADDLED",
    "GIVE_WAY",
    "PADDLE",
    "STRETCH_OUT",
    "EASY_OARS",
    "HOLD_WATER",
    # boarding
    "Boarded",
    "GrappleResult",
    "can_grapple",
    "still_holding",
    "relative_speed",
    "velocity",
    "within_reach",
    "bears_alongside",
    "GRAPNEL_RANGE",
    "MAX_BOARDING_CLOSURE",
    "MAX_HOLDING_CLOSURE",
    # weather
    "Weather",
    "MaritimeWeatherProvider",
    "FlatWeatherProvider",
    "sea_state_for",
    "sea_drag",
    "SEA_STATES",
    # sailing
    "WindVector",
    "PolarCurve",
    "SailPlan",
    "SAIL_PLANS",
    "FURLED",
    "STORM",
    "REEFED",
    "WORKING",
    "FULL",
    "sail_plan",
    "relative_wind_angle",
    "achievable_speed",
    "leeway_angle",
    # tactical geometry
    "relative_heading",
    "aspect",
    "aspect_name",
    "closure",
    "time_to_close",
    "range_band",
    "bears",
    "arcs_bearing",
    "crossing_the_t",
    "ARCS",
    # observation
    "horizon_distance",
    "geographic_range",
    "detection_limit",
    "detection_level",
    "bearing_in_points",
    "sight",
    "scan",
    "Sighting",
    "DETECTION_LEVELS",
    "CONTACT",
    "CLASSIFIED",
    "IDENTIFIED",
    "traffic",
    "VesselTraffic",
    # grounding
    "keel_clearance",
    "check_grounding",
    "check_swept_grounding",
    "hull_points",
    "sweep_positions",
    "is_shoaling",
    "refloats_on_tide",
    "GroundingResult",
    "TOUCHED",
    "AGROUND",
    "HOLED",
    # motion
    "MotionState",
    "MotionLimits",
    "HelmOrders",
    "advance",
    "DEFAULT_REGION",
    # events
    "Event",
    "EventBus",
    "Delivery",
    # results
    "Result",
    "NOT_PERMITTED",
    "PRECONDITION_FAILED",
    "INVALID_TARGET",
    "UNSUPPORTED",
)
